// Package gen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package gen

import (
	"time"
)

// Attributes defines model for Attributes.
type Attributes map[string]string

// Message defines model for Message.
type Message struct {
	Attributes  *Attributes `json:"attributes,omitempty"`
	Data        string      `json:"data"`
	MessageId   string      `json:"messageId"`
	PublishTime time.Time   `json:"publishTime"`
}

// Request defines model for Request.
type Request struct {
	DeliveryAttempt float32 `json:"deliveryAttempt"`
	Message         Message `json:"message"`
	Subscription    string  `json:"subscription"`
}

// N400BadRequest defines model for 400BadRequest.
type N400BadRequest struct {
	Code  int    `json:"code"`
	Error string `json:"error"`
}

// N500InternalServerError defines model for 500InternalServerError.
type N500InternalServerError struct {
	Code  int    `json:"code"`
	Error string `json:"error"`
}

// EmailUserCreatedJSONRequestBody defines body for EmailUserCreated for application/json ContentType.
type EmailUserCreatedJSONRequestBody = Request
