// Package gen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package gen

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// DateTime defines model for DateTime.
type DateTime = time.Time

// Email defines model for Email.
type Email = string

// Language defines model for Language.
type Language = string

// Text defines model for Text.
type Text = string

// UUID defines model for UUID.
type UUID = openapi_types.UUID

// User defines model for User.
type User struct {
	CreatedAt DateTime `json:"createdAt"`
	Email     *Email   `json:"email,omitempty"`
	Id        UUID     `json:"id"`
	Language  Language `json:"language"`
}

// N400BadRequest defines model for 400BadRequest.
type N400BadRequest struct {
	Code  int    `json:"code"`
	Error string `json:"error"`
}

// N500InternalServerError defines model for 500InternalServerError.
type N500InternalServerError struct {
	Code  int    `json:"code"`
	Error string `json:"error"`
}

// UpsertUserJSONBody defines parameters for UpsertUser.
type UpsertUserJSONBody struct {
	Email    Email    `json:"email"`
	Language Language `json:"language"`
	Name     *Text    `json:"name,omitempty"`
}

// UpsertUserJSONRequestBody defines body for UpsertUser for application/json ContentType.
type UpsertUserJSONRequestBody UpsertUserJSONBody
