name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Actions checkout
        uses: actions/checkout@v4

      - name: Run linter
        uses: ./.github/actions/lint

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Actions checkout
        uses: actions/checkout@v4

      - name: Run tests
        uses: ./.github/actions/tests
