name: Deploy production

on:
  release:
    types: created
    
permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  dockerize:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        target: ["api", "worker"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_DEPLOY_SA }}
        export_default_credentials: true

    - name: Login to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_DEPLOY_SA }}

    - name: dockerize
      uses: ./.github/actions/dockerize
      with:
        project: ${{ env.GCP_PROJECT }}
        service_account: ${{ secrets.GCP_DEPLOY_SA }}
        service: ${{ matrix.target }}

  deploy:
    runs-on: ubuntu-latest
    needs: dockerize
    environment: production
    strategy:
      matrix:
        target: ["api", "worker"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_DEPLOY_SA }}
        export_default_credentials: true

    - name: Login to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_DEPLOY_SA }}

    - name: Retrieve secret from Secret Manager
      id: secrets
      uses: google-github-actions/get-secretmanager-secrets@v2
      with:
        secrets: |
          env:${{ env.GCP_PROJECT }}/backend-env

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: backend-${{ matrix.target }}
        image: us-central1-docker.pkg.dev/${{ env.GCP_PROJECT }}/backend/${{ matrix.target }}:latest
        region: us-central1
        env_vars: ${{ steps.secrets.outputs.env }}
        env_vars_update_strategy: overwrite
